import { Step } from "react-joyride";

export const tourSteps: Step[] = [
  {
    target: ".name-generator", // Target the main container
    content: "Generate names for your collections here.",
    disableBeacon: true,
  },
  {
    target: ".name-input", // Target the name input field
    content: "Enter a name to add to the list.",
  },
  {
    target: ".add-name-button", // Target the add name button
    content: "Click here to add the name to the list.",
  },
  {
    target: ".spin-button", // Target the spin button
    content: "Click to spin the wheel and generate a random name.",
  },
  {
    target: ".generated-name-display", // Target the generated name display
    content: "This is the name generated by the wheel.",
  },
  {
    target: ".wheel-segment", // Target the wheel segments
    content: "These are the names currently on the wheel.",
  },
  {
    target: ".toggle-right-side-button", // Target the toggle button for the right side
    content: "Click here to show or hide the name list.",
  },
  // Add more steps as needed
];
