"""add_feedback_table

Revision ID: 14cd3a0934af
Revises: 34ecb91517cf
Create Date: 2024-11-22 08:39:15.675861

"""
from typing import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '14cd3a0934af'
down_revision: str | None = '34ecb91517cf'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feedback', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'feedback', 'users', ['user_id'], ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'feedback', type_='foreignkey')
    op.drop_column('feedback', 'user_id')
    # ### end Alembic commands ###
