"""Add stage to CollectionCreate

Revision ID: 23ab397f408d
Revises: 2fa6e48af3f3
Create Date: 2024-10-17 12:38:54.863489

"""
from typing import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '23ab397f408d'
down_revision: str | None = '2fa6e48af3f3'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
