"""Add stage column to collections table

Revision ID: 2fa6e48af3f3
Revises: d48985a79c54
Create Date: 2024-10-17 11:56:27.057123

"""
from typing import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2fa6e48af3f3'
down_revision: str | None = 'd48985a79c54'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('collections', 'stage',
               existing_type=postgresql.ENUM('beginner', 'intermediate', 'advanced', name='stage_enum'),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False,
               existing_server_default=sa.text("'beginner'::stage_enum"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('collections', 'stage',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=postgresql.ENUM('beginner', 'intermediate', 'advanced', name='stage_enum'),
               existing_nullable=False,
               existing_server_default=sa.text("'beginner'::stage_enum"))
    # ### end Alembic commands ###
