"""Add category to collections

Revision ID: 3292df1241b5
Revises: 3c4b687d38c6
Create Date: 2024-08-09 14:34:55.868597

"""
from typing import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '3292df1241b5'
down_revision: str | None = '3c4b687d38c6'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'collections', 
        sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default='All Collections')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('collections', 'category')
    # ### end Alembic commands ###
