"""add_indexes_and_mountain_time

Revision ID: 7da831e7d874
Revises: c0070990eaec
Create Date: 2024-12-11 16:10:59.289849

"""
from typing import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql
from models import MountainDateTime

# revision identifiers, used by Alembic.
revision: str = '7da831e7d874'
down_revision: str | None = 'c0070990eaec'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_collection_completion', 'completion_records', ['collection_id'], unique=False)
    op.create_index('idx_user_completion', 'completion_records', ['user_id', 'completed_at'], unique=False)
    
    # For the datetime conversion, we'll use the base PostgreSQL timestamp type
    # since MountainDateTime is a runtime type converter
    op.alter_column('completion_records', 'completed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_user_completion', table_name='completion_records')
    op.drop_index('idx_collection_completion', table_name='completion_records')
    op.alter_column('completion_records', 'completed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    # ### end Alembic commands ###
