"""Add created_at to collections

Revision ID: 8b7be4abe74a
Revises: f79c53c79ea3
Create Date: 2024-08-06 15:57:40.252735

"""
from typing import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b7be4abe74a'
down_revision: str | None = 'f79c53c79ea3'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'collections', 
        sa.Column(
            'created_at', 
            sa.DateTime(), 
            nullable=False, 
            server_default=sa.func.now()  # Add this line to set a default value
        )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('collections', 'created_at')
    # ### end Alembic commands ###
