"""add_feedback_and_mountain_time

Revision ID: cb9d8caf77a1
Revises: e0f61379ad1d
Create Date: 2024-11-27 16:52:11.910896

"""
from typing import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'cb9d8caf77a1'
down_revision: str | None = 'e0f61379ad1d'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
