"""Add count field to Item model

Revision ID: e0f61379ad1d
Revises: adc89c731776
Create Date: 2024-11-27 16:32:28.976926

"""
from typing import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e0f61379ad1d'
down_revision: str | None = 'adc89c731776'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'count')
    # ### end Alembic commands ###
