"""Remove user_email

Revision ID: e1871249dcf8
Revises: caf3d8f47d1a
Create Date: 2024-11-13 22:14:46.211462

"""
from typing import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e1871249dcf8'
down_revision: str | None = 'caf3d8f47d1a'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('feedback', 'user_email')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feedback', sa.Column('user_email', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
