"""Updated models

Revision ID: fd285411f6e9
Revises: 3292df1241b5
Create Date: 2024-08-19 18:21:56.569797

"""
from typing import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'fd285411f6e9'
down_revision: str | None = '3292df1241b5'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('collections', 'category')
    op.drop_column('users', 'hashed_password')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('hashed_password', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('collections', sa.Column('category', sa.VARCHAR(), server_default=sa.text("'All Collections'::character varying"), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
